name: Driving Test Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    - name: Run the bot
      run: python driving_test_bot.py
